# Generated by Django 2.0.1 on 2018-04-09 08:43

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_id', models.CharField(max_length=32, verbose_name='设备编号')),
                ('dev_name', models.CharField(max_length=128, verbose_name='设备名称/用途')),
                ('procur_project', models.CharField(max_length=128, verbose_name='购置项目名称')),
                ('dev_sn', models.CharField(max_length=32, verbose_name='设备SN号')),
                ('dev_pn', models.CharField(max_length=32, verbose_name='设备PN号')),
                ('dev_type', models.CharField(choices=[('*', '未归类设备'), ('1', '普通PC机'), ('2', '机架服务器'), ('3', '防火墙'), ('4', '交换机'), ('5', '路由器'), ('6', 'NAS/SAN/存储'), ('7', 'USBKey')], max_length=2, verbose_name='设备类型')),
                ('dev_brand', models.CharField(choices=[('10', '联想'), ('11', 'IBM'), ('12', '惠普'), ('13', 'DELL'), ('14', '华为'), ('31', '天融信'), ('32', '思科'), ('33', 'F5'), ('34', 'EMC'), ('35', '群晖')], max_length=2, verbose_name='设备品牌')),
                ('dev_model', models.CharField(max_length=32, verbose_name='设备型号')),
                ('pur_date', models.DateField(blank=True, null=True, verbose_name='采购日期')),
                ('use_date', models.DateField(blank=True, null=True, verbose_name='上线日期')),
                ('warranty_exp', models.CharField(choices=[('0', '无质保信息'), ('1', '一年保'), ('2', '两年保'), ('3', '三年保'), ('5', '五年保')], max_length=2, verbose_name='质保年限')),
                ('dev_status', models.CharField(choices=[('0', '正常运行'), ('1', '准备上线'), ('2', '准备下线'), ('3', '停止服务'), ('4', '损坏停服'), ('5', '已报废处理')], max_length=1, verbose_name='设备状态')),
                ('remark', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='备注信息')),
            ],
            options={
                'verbose_name_plural': '设备基本信息',
                'verbose_name': '设备基本信息',
            },
        ),
        migrations.CreateModel(
            name='DevHardwareList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw_type', models.CharField(choices=[('1', 'CPU'), ('2', '内存'), ('3', '硬盘'), ('4', '光驱'), ('5', '电源'), ('6', '网卡')], max_length=2, verbose_name='硬件类型')),
                ('num_sum', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('hw_desc', models.CharField(blank=True, max_length=128, null=True, verbose_name='硬件描述')),
                ('dev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.DevBaseInfo', verbose_name='设备编号')),
            ],
            options={
                'verbose_name_plural': '设备硬件信息',
                'verbose_name': '设备硬件信息',
            },
        ),
        migrations.CreateModel(
            name='DevMaintInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_position', models.CharField(max_length=64, verbose_name='设备位置')),
                ('cabinet_space', models.CharField(max_length=64, verbose_name='机柜位置')),
                ('coherent_sys', models.CharField(max_length=128, verbose_name='关联系统')),
                ('os_type', models.CharField(choices=[('10', 'WINDOWS2003'), ('11', 'WINDOWS2008'), ('12', 'WINDOWS2012'), ('13', 'WINDOWS2016'), ('50', 'RHEL5-OEL5'), ('51', 'RHEL6-OEL6'), ('52', 'RHEL7-OEL7')], max_length=2, verbose_name='操作系统')),
                ('dev_rank', models.CharField(choices=[('1', '交易系统'), ('2', '业务系统'), ('3', '管理系统')], max_length=2, verbose_name='设备等级')),
                ('supplier_name', models.CharField(max_length=32, verbose_name='供货商')),
                ('maint_unit', models.CharField(max_length=32, verbose_name='维保单位')),
                ('maint_unit_tel', models.CharField(max_length=32, verbose_name='维保联系电话')),
                ('responsible', models.CharField(max_length=32, verbose_name='运维责任人')),
                ('dev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.DevBaseInfo', verbose_name='设备编号')),
            ],
            options={
                'verbose_name_plural': '设备维保信息',
                'verbose_name': '设备维保信息',
            },
        ),
        migrations.CreateModel(
            name='MaintRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainta_date', models.DateField(verbose_name='维修日期')),
                ('instructions', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='维修项目说明')),
                ('dev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.DevBaseInfo', verbose_name='设备编号')),
            ],
            options={
                'verbose_name_plural': '设备维保记录',
                'verbose_name': '设备维保记录',
            },
        ),
        migrations.AlterUniqueTogether(
            name='devbaseinfo',
            unique_together={('dev_id',)},
        ),
        migrations.AlterIndexTogether(
            name='devbaseinfo',
            index_together={('dev_name',)},
        ),
    ]
