# Generated by Django 2.0.1 on 2018-03-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commset', '0002_sysdictname_dict_en_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sysdictitem',
            options={'ordering': ('dict_name', 'dict_item', 'dict_item_name'), 'verbose_name': '系统字典', 'verbose_name_plural': '系统字典'},
        ),
        migrations.AlterModelOptions(
            name='sysdictname',
            options={'ordering': ('dict_name',)},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('0', '保密'), ('1', '男'), ('2', '女')], default='3', max_length=8, verbose_name='性别'),
        ),
    ]
