# Generated by Django 2.0.1 on 2018-03-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commset', '0004_auto_20180325_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_en_name', models.CharField(max_length=32, verbose_name='参数简码')),
                ('param_name', models.CharField(max_length=128, verbose_name='参数名称')),
                ('param_value', models.CharField(max_length=128, verbose_name='参数值')),
                ('param_type', models.CharField(choices=[('0', '隐藏'), ('1', '可见'), ('2', '可修改'), ('3', '可删除')], default='3', max_length=8, verbose_name='参数操作标识')),
                ('param_cls', models.CharField(choices=[('1', '全局参数'), ('2', '网络管理'), ('3', '备份任务')], default='1', max_length=2, verbose_name='参数分类')),
                ('param_status', models.CharField(choices=[('N', '暂停处理'), ('Y', '允许处理')], default='1', max_length=1, null=True, verbose_name='处理标识')),
            ],
            options={
                'verbose_name_plural': '系统参数',
                'ordering': ('param_name',),
                'verbose_name': '系统参数',
            },
        ),
        migrations.RemoveField(
            model_name='sysdictname',
            name='dict_type',
        ),
        migrations.AddField(
            model_name='sysdictname',
            name='dict_cls',
            field=models.CharField(choices=[('1', '全局参数'), ('2', '网络管理'), ('3', '备份任务')], default='0', max_length=1, verbose_name='字典类别'),
        ),
    ]
