# Generated by Django 2.0.1 on 2018-03-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commset', '0006_auto_20180326_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysdictname',
            name='dict_cls',
            field=models.CharField(choices=[('1', '全局参数'), ('2', '系统管理'), ('3', 'IP地址管理'), ('4', '备份任务管理'), ('5', '机构业务')], default='0', max_length=1, verbose_name='字典类别'),
        ),
        migrations.AlterField(
            model_name='sysparam',
            name='param_cls',
            field=models.CharField(choices=[('1', '全局参数'), ('2', '系统管理'), ('3', 'IP地址管理'), ('4', '备份任务管理'), ('5', '机构业务')], default='1', max_length=2, verbose_name='参数分类'),
        ),
        migrations.AlterField(
            model_name='sysparam',
            name='param_status',
            field=models.CharField(choices=[('N', '暂停处理'), ('Y', '允许处理')], default='Y', max_length=1, null=True, verbose_name='处理标识'),
        ),
    ]
