# Generated by Django 2.0.1 on 2018-04-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commset', '0007_auto_20180327_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookset', models.CharField(max_length=1, verbose_name='关联模块名称')),
                ('physical_date', models.CharField(max_length=8, verbose_name=' 物理日期')),
                ('date_flag', models.CharField(max_length=1, verbose_name='日期标志')),
                ('date_status', models.CharField(max_length=1, verbose_name='日期状态')),
            ],
            options={
                'verbose_name_plural': '交易日历',
                'verbose_name': '交易日历',
                'ordering': ('physical_date',),
            },
        ),
    ]
