# Generated by Django 2.0.1 on 2018-04-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commset', '0009_auto_20180407_1419'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='calendar',
            index_together={('physical_date', 'date_flag')},
        ),
    ]
