# Generated by Django 2.0.1 on 2018-04-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commset', '0010_auto_20180407_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='date_flag',
            field=models.CharField(choices=[('0', '非清算日'), ('1', '清算日')], max_length=1, verbose_name='日期标志'),
        ),
    ]
