# Generated by Django 2.0.1 on 2018-04-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commset', '0012_auto_20180407_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='二级菜单名称')),
                ('url', models.CharField(max_length=128, verbose_name='链接目标')),
                ('icon', models.CharField(max_length=128, verbose_name='图标链接')),
                ('sort_rule', models.IntegerField(verbose_name='排序规则')),
                ('flag', models.CharField(choices=[('N', '暂停处理'), ('Y', '允许处理')], default='Y', max_length=1, null=True, verbose_name='处理标识')),
            ],
            options={
                'verbose_name_plural': '菜单名称',
                'verbose_name': '菜单名称',
                'ordering': ('sort_rule',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='menulist',
            unique_together={('url',)},
        ),
    ]
