# Generated by Django 2.0.1 on 2018-04-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commset', '0013_auto_20180407_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menulist',
            options={'ordering': ('sort_rule',), 'verbose_name': '菜单设置', 'verbose_name_plural': '菜单设置'},
        ),
        migrations.AddField(
            model_name='menulist',
            name='titleA',
            field=models.CharField(choices=[('1', '全局参数'), ('2', '系统管理'), ('3', 'IP地址管理'), ('4', '备份任务管理'), ('5', '机构业务')], default='', max_length=64, verbose_name='一级菜单名称'),
            preserve_default=False,
        ),
    ]
