# Generated by Django 2.0.1 on 2018-03-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insbusi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inserneworginfo',
            name='central_org',
            field=models.CharField(max_length=8, verbose_name='中心营业部编码'),
        ),
        migrations.AlterField(
            model_name='inserneworginfo',
            name='org_code',
            field=models.CharField(max_length=8, verbose_name='营业部编码'),
        ),
        migrations.AlterField(
            model_name='inserneworginfo',
            name='org_fname',
            field=models.CharField(max_length=64, verbose_name='营业部全称'),
        ),
    ]
