# Generated by Django 2.0.1 on 2018-03-27 12:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insbusi', '0002_auto_20180327_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='InserNewOrgInfoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oper_sys', models.CharField(max_length=32, verbose_name='处理系统名称')),
                ('insert_org_flag', models.CharField(max_length=1, verbose_name='流程标识')),
                ('insert_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='执行时间')),
                ('log_txt', models.TextField(blank=True, verbose_name='日志记录')),
            ],
            options={
                'verbose_name': '营业部添加日志',
                'verbose_name_plural': '营业部添加日志',
            },
        ),
        migrations.AlterModelOptions(
            name='inserneworginfo',
            options={'ordering': ('org_code',), 'verbose_name': '批量加新营业部', 'verbose_name_plural': '批量加新营业部'},
        ),
        migrations.AlterField(
            model_name='inserneworginfo',
            name='central_org',
            field=models.CharField(blank=True, max_length=8, verbose_name='中心营业部编码'),
        ),
        migrations.AlterField(
            model_name='inserneworginfo',
            name='insert_org_flag',
            field=models.CharField(choices=[('0', '待处理'), ('1', '全部完成'), ('2', '暂不处理'), ('3', '账户系统已处理')], default='0', max_length=1, verbose_name='流程标识'),
        ),
        migrations.AddField(
            model_name='inserneworginfolog',
            name='org_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insbusi.InserNewOrgInfo', verbose_name='营业部编码'),
        ),
    ]
