# Generated by Django 2.0.1 on 2018-03-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insbusi', '0003_auto_20180327_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inserneworginfolog',
            name='insert_org_flag',
        ),
    ]
