# Generated by Django 2.0.1 on 2018-03-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insbusi', '0005_runscriptslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='runscriptslist',
            name='run_path',
            field=models.TextField(default='', verbose_name='执行路径'),
            preserve_default=False,
        ),
    ]
