# Generated by Django 2.0.1 on 2018-03-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insbusi', '0006_runscriptslist_run_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runscriptslist',
            name='run_status',
            field=models.CharField(default='0', max_length=1, verbose_name='执行状态'),
        ),
    ]
