# Generated by Django 2.0.1 on 2018-03-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insbusi', '0007_auto_20180328_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='runscriptslist',
            name='script_desc',
            field=models.CharField(default='', max_length=128, verbose_name='函数说明'),
            preserve_default=False,
        ),
    ]
