# Generated by Django 2.0.1 on 2018-03-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insbusi', '0008_runscriptslist_script_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='runscriptslist',
            name='run_param',
            field=models.TextField(default='', verbose_name='执行参数'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='runscriptslist',
            name='run_path',
            field=models.CharField(max_length=128, verbose_name='执行路径'),
        ),
    ]
