# Generated by Django 2.0.1 on 2018-03-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insbusi', '0009_auto_20180328_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runscriptslist',
            name='run_status',
            field=models.CharField(choices=[('0', '暂停'), ('1', '运行中'), ('2', '执行异常')], default='0', max_length=1, verbose_name='执行状态'),
        ),
    ]
