# Generated by Django 2.0.1 on 2018-04-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insbusi', '0010_auto_20180329_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='inserneworginfolog',
            name='task_status',
            field=models.CharField(choices=[('1', '完成'), ('2', '忽略'), ('3', '失败')], default='3', max_length=1, verbose_name='任务处理结果'),
        ),
        migrations.AlterField(
            model_name='inserneworginfo',
            name='insert_org_flag',
            field=models.CharField(choices=[('0', '待处理'), ('1', '全部完成'), ('2', '暂不处理')], default='0', max_length=1, verbose_name='流程标识'),
        ),
    ]
