# Generated by Django 2.0.1 on 2018-04-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insbusi', '0011_auto_20180402_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inserneworginfolog',
            name='oper_sys',
            field=models.CharField(max_length=128, verbose_name='处理系统名称'),
        ),
    ]
