"""
Django settings for YwzcWebSys project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
from __future__ import absolute_import

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 增加扩展搜索路径 ADD SlovEnt
import sys
sys.path.insert(0,os.path.join(BASE_DIR,'apps'))
sys.path.insert(0,os.path.join(BASE_DIR,'extapps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'oeo%i^3=m59hyi1-j3i(pf=(q1y3h24p#b_p-udrs1!)gy)v%3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition
# AUTHENTICATION_BACKENDS = (
#     'Users.views.CustomBackend',
# )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 注册自定义的apps
    'apps.commset',                          # 系统通用设置
    'apps.netmget',                          # IP地址管理
    'apps.backtaskmget',                    # 备份任务管理
    'apps.insbusi',                          # 机构业务
    'apps.runscripts',                       # 后台函数执行管理
    'device',                                 # 设备信息登记

    # 注册xadmin
    'xadmin',
    'crispy_forms',
    'DjangoUeditor',

]

# 此处重载是为了使我们的UserProfile生效
AUTH_USER_MODEL = "commset.UserProfile"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'YwzcWebSys.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'YwzcWebSys.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

from commset.Config import Get_ConfigInfo
globalsConfigFile =  BASE_DIR + r"\apps\commset\Config.ini"
globParaInfo = Get_ConfigInfo(globalsConfigFile)

DB_NAME = globParaInfo["DB_NAME"]
USER_NAME = globParaInfo["USER_NAME"]
USER_PWD = globParaInfo["USER_PWD"]
DB_HOST = globParaInfo["DB_HOST"]
DB_PORT = globParaInfo["DB_PORT"]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':      DB_NAME,
        'USER':      USER_NAME,
        'PASSWORD': USER_PWD,
        'HOST':      DB_HOST,
        'PORT':      DB_PORT,
         'OPTIONS': {
             'autocommit': True,
             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
         },
    }
}

# from SEDefFuncPack import torndb
# mySqlConn = torndb.Connection(
#     "%s:%s" % (DB_HOST, DB_PORT),
#     DB_NAME,
#     USER_NAME,
#     USER_PWD,
# )

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

# 语言改为中文
LANGUAGE_CODE = 'zh-hans'

# 时区改为上海
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# 数据库存储使用时间，True时间会被存为UTC的时间
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# TEMPLATE_DIRS = (os.path.join(BASE_DIR,  'templates'),)

# 设置上传文件的路径
MEDIA_URL = '/upload/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'upload')
