# Generated by Django 2.0.1 on 2018-03-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.GenericIPAddressField(verbose_name='IP地址')),
                ('net_tags', models.GenericIPAddressField(verbose_name='所属网段')),
                ('sub_mask', models.GenericIPAddressField(verbose_name='子网掩码')),
                ('gateway', models.GenericIPAddressField(verbose_name='网关地址')),
                ('use_object', models.CharField(max_length=255, null=True, verbose_name='使用对象')),
                ('remark', models.TextField(null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name_plural': 'IP地址管理',
                'verbose_name': 'IP地址管理',
            },
        ),
    ]
