# Generated by Django 2.0.1 on 2018-03-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netmget', '0002_auto_20180326_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Net91Manage',
            fields=[
            ],
            options={
                'verbose_name': '10.0.91.0',
                'proxy': True,
                'verbose_name_plural': '10.0.91.0',
                'indexes': [],
            },
            bases=('netmget.ipmanage',),
        ),
    ]
