# Generated by Django 2.0.1 on 2018-03-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBBackTaskSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('host_ip', models.GenericIPAddressField(verbose_name='主机IP')),
                ('host_user', models.CharField(max_length=16, verbose_name='系统用户名')),
                ('host_user_passwd', models.CharField(max_length=128, verbose_name='用户密码')),
                ('db_type', models.CharField(choices=[('MSSQL', 'MSSQL'), ('MYSQL', 'MYSQL'), ('ORACLE', 'ORACLE')], default='ORACLE', max_length=4, null=True, verbose_name='数据库类型')),
                ('db_sid', models.CharField(max_length=16, verbose_name='数据库SID')),
                ('db_user', models.CharField(max_length=4, verbose_name='数据库用户')),
                ('db_user_passwd', models.CharField(max_length=4, verbose_name='数据库用户密码')),
                ('is_compre', models.CharField(choices=[('N', '否'), ('Y', '是')], default='Y', max_length=1, verbose_name='是否压缩')),
                ('compre_type', models.CharField(choices=[('RAR', '使用RAR压缩'), ('TAR', '使用TAR压缩'), ('ZIP', '使用zip压缩')], default='RAR', max_length=8, verbose_name='压缩方式')),
                ('compre_passwd', models.CharField(max_length=32, verbose_name='压缩密码')),
                ('file_save_path', models.FilePathField(verbose_name='文件保存路径')),
                ('names_of_backdb', models.CharField(max_length=128, verbose_name='备份库列表')),
                ('reserved_day', models.IntegerField(max_length=4, verbose_name='备份天数')),
                ('proc_flag', models.CharField(choices=[('N', '暂停处理'), ('Y', '允许处理')], default='Y', max_length=1, verbose_name='处理标识')),
                ('task_run_time', models.DateTimeField(verbose_name='任务执行时间')),
                ('enforce_flag', models.CharField(choices=[('N', '暂停处理'), ('Y', '允许处理')], default='N', max_length=4, verbose_name='强制处理标识')),
            ],
            options={
                'verbose_name': '数据库备份任务',
                'ordering': ('task_name',),
                'verbose_name_plural': '数据库备份任务',
            },
        ),
    ]
