# Generated by Django 2.0.1 on 2018-03-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtaskmget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbbacktaskset',
            name='reserved_day',
            field=models.IntegerField(verbose_name='备份天数'),
        ),
    ]
