# Generated by Django 2.0.1 on 2018-03-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtaskmget', '0002_auto_20180326_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbbacktaskset',
            name='task_run_time',
            field=models.TimeField(verbose_name='任务执行时间'),
        ),
    ]
