# Generated by Django 2.0.1 on 2018-03-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtaskmget', '0003_auto_20180326_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBBackTaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('task_run_date', models.DateField(verbose_name='任务执行日期')),
                ('task_run_time', models.TimeField(verbose_name='任务执行时间')),
                ('host_ip', models.GenericIPAddressField(verbose_name='主机IP')),
                ('db_type', models.CharField(choices=[('MSSQL', 'MSSQL'), ('MYSQL', 'MYSQL'), ('ORACLE', 'ORACLE')], default='ORACLE', max_length=4, verbose_name='数据库类型')),
                ('names_of_backdb', models.CharField(max_length=512, verbose_name='备份库列表')),
                ('file_name', models.FilePathField(verbose_name='归档文件名')),
                ('compre_type', models.CharField(choices=[('RAR', '使用RAR压缩'), ('TAR', '使用TAR压缩'), ('ZIP', '使用zip压缩')], default='RAR', max_length=8, verbose_name='压缩方式')),
                ('file_save_path', models.FilePathField(verbose_name='原始路径')),
                ('arch_nas_path', models.FilePathField(verbose_name='归档路径')),
                ('compre_passwd', models.CharField(max_length=32, verbose_name='压缩密码')),
                ('file_siz', models.FilePathField(verbose_name='文件大小（kb）')),
                ('md5_string', models.CharField(max_length=1024, verbose_name='MD5校验码')),
                ('remark', models.TextField(verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '数据库备份日志',
                'verbose_name_plural': '数据库备份日志',
                'ordering': ('task_name', 'task_run_date', 'task_run_time'),
            },
        ),
        migrations.AlterField(
            model_name='dbbacktaskset',
            name='names_of_backdb',
            field=models.CharField(max_length=512, verbose_name='备份库列表'),
        ),
        migrations.AlterField(
            model_name='dbbacktaskset',
            name='reserved_day',
            field=models.IntegerField(verbose_name='备份保留天数'),
        ),
    ]
