# Generated by Django 2.0.1 on 2018-03-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtaskmget', '0006_auto_20180326_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbbacktaskset',
            name='compre_passwd',
        ),
        migrations.AddField(
            model_name='dbbacktaskset',
            name='is_compre_passwd',
            field=models.CharField(choices=[('N', '不需要'), ('Y', '需要')], default='Y', max_length=32, verbose_name='是否加密压缩'),
        ),
    ]
