# Generated by Django 2.0.1 on 2018-03-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtaskmget', '0007_auto_20180326_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbbacktasklog',
            name='arch_nas_path',
            field=models.CharField(max_length=255, verbose_name='归档路径'),
        ),
        migrations.AlterField(
            model_name='dbbacktasklog',
            name='file_save_path',
            field=models.CharField(max_length=255, verbose_name='原始路径'),
        ),
        migrations.AlterField(
            model_name='dbbacktaskset',
            name='file_save_path',
            field=models.CharField(max_length=255, verbose_name='文件保存路径'),
        ),
    ]
