# Generated by Django 2.0.1 on 2018-03-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtaskmget', '0009_auto_20180329_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbbacktasklog',
            name='file_siz',
            field=models.IntegerField(verbose_name='文件大小（kb）'),
        ),
        migrations.AlterField(
            model_name='filebacktasklog',
            name='file_siz',
            field=models.IntegerField(verbose_name='文件大小（kb）'),
        ),
    ]
