# Generated by Django 2.0.1 on 2018-03-29 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtaskmget', '0010_auto_20180329_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBackTaskExcludeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclude_list', models.CharField(max_length=256, verbose_name='排除名单')),
                ('proc_flag', models.CharField(choices=[('N', '暂停处理'), ('Y', '允许处理')], default='Y', max_length=1, verbose_name='处理标识')),
                ('task_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backtaskmget.FileBackTaskSet', verbose_name='任务名称')),
            ],
            options={
                'verbose_name': '文件备份排除列表',
                'ordering': ('task_name', 'exclude_list'),
                'verbose_name_plural': '文件备份排除列表',
            },
        ),
    ]
