# Generated by Django 2.0.1 on 2018-03-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtaskmget', '0013_auto_20180329_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebacktaskexcludeset',
            name='proc_flag',
            field=models.CharField(default='Y', max_length=1, verbose_name='处理标识'),
        ),
    ]
