# Generated by Django 2.0.1 on 2018-03-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtaskmget', '0015_auto_20180329_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filebacktaskexcludeset',
            options={'verbose_name': '文件备份排除列表', 'verbose_name_plural': '文件备份排除列表'},
        ),
    ]
