# Generated by Django 2.0.1 on 2018-03-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtaskmget', '0016_auto_20180330_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebacktaskexcludeset',
            name='proc_flag',
            field=models.CharField(choices=[('N', '暂停处理'), ('Y', '允许处理')], default='Y', max_length=1, verbose_name='处理标识'),
        ),
        migrations.AlterField(
            model_name='filebacktasklog',
            name='arch_nas_path',
            field=models.CharField(max_length=1024, verbose_name='归档路径'),
        ),
        migrations.AlterField(
            model_name='filebacktasklog',
            name='file_name',
            field=models.CharField(max_length=1024, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='filebacktasklog',
            name='file_save_path',
            field=models.CharField(max_length=1024, verbose_name='原始路径'),
        ),
    ]
