# Generated by Django 2.0.1 on 2018-03-31 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtaskmget', '0018_auto_20180331_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebacktasklog',
            name='arch_nas_path',
            field=models.CharField(max_length=256, verbose_name='归档路径'),
        ),
        migrations.AlterField(
            model_name='filebacktasklog',
            name='file_save_path',
            field=models.CharField(max_length=256, verbose_name='原始路径'),
        ),
    ]
