# Generated by Django 2.0.1 on 2018-04-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtaskmget', '0021_filebacktasklog_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbbacktaskset',
            old_name='host_user',
            new_name='os_user',
        ),
        migrations.RemoveField(
            model_name='dbbacktaskset',
            name='host_user_passwd',
        ),
        migrations.AddField(
            model_name='dbbacktaskset',
            name='arch_nas_passwd',
            field=models.CharField(default='', max_length=128, verbose_name='NAS归档密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dbbacktaskset',
            name='arch_nas_user',
            field=models.CharField(default='', max_length=32, verbose_name='NAS归档用户名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dbbacktaskset',
            name='os_type',
            field=models.CharField(choices=[('1', 'WINDOWS2008'), ('2', 'WINDOWS2012'), ('3', 'RHEL6-OEL6'), ('4', 'RHEL7-OEL7')], default='', max_length=2, verbose_name='系统类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dbbacktaskset',
            name='os_user_passwd',
            field=models.CharField(default='', max_length=128, verbose_name='系统用户密码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dbbacktaskset',
            name='arch_nas_path',
            field=models.CharField(max_length=255, verbose_name='NAS归档路径'),
        ),
        migrations.AlterField(
            model_name='dbbacktaskset',
            name='file_save_path',
            field=models.CharField(max_length=255, verbose_name='本地保存路径'),
        ),
        migrations.AlterField(
            model_name='dbbacktaskset',
            name='reserved_day',
            field=models.IntegerField(verbose_name='本地备份文件保留天数'),
        ),
    ]
