# Generated by Django 2.0.1 on 2018-04-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtaskmget', '0022_auto_20180401_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebacktasklog',
            name='task_status',
            field=models.CharField(choices=[('0', '处理中'), ('1', '完成'), ('2', '忽略'), ('3', '失败')], max_length=1, verbose_name='任务状态'),
        ),
    ]
