# Generated by Django 2.0.1 on 2018-04-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtaskmget', '0023_auto_20180402_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbbacktaskset',
            name='os_type',
            field=models.CharField(choices=[('10', 'WINDOWS2003'), ('11', 'WINDOWS2008'), ('12', 'WINDOWS2012'), ('13', 'WINDOWS2016'), ('50', 'RHEL5-OEL5'), ('51', 'RHEL6-OEL6'), ('52', 'RHEL7-OEL7')], max_length=2, verbose_name='系统类型'),
        ),
    ]
